//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.2.250604.1+b02a3ee244
//       
//       Command:
//           LottieGen -Language CSharp -Namespace LocalSendDotNet -Public -WinUIVersion 3.0 -InputFile SplashLogo.json
//       
//       Input file:
//           SplashLogo.json (47716 bytes created 14:23+08:00 Aug 15 2026)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ____________________________________
// |       Object stats       | Count |
// |__________________________|_______|
// | All CompositionObjects   |   156 |
// |--------------------------+-------|
// | Expression animators     |    14 |
// | KeyFrame animators       |    16 |
// | Reference parameters     |    14 |
// | Expression operations    |     0 |
// |--------------------------+-------|
// | Animated brushes         |     4 |
// | Animated gradient stops  |    13 |
// | ExpressionAnimations     |     8 |
// | PathKeyFrameAnimations   |     - |
// |--------------------------+-------|
// | ContainerVisuals         |     1 |
// | ShapeVisuals             |     1 |
// |--------------------------+-------|
// | ContainerShapes          |     1 |
// | CompositionSpriteShapes  |    12 |
// |--------------------------+-------|
// | Brushes                  |     8 |
// | Gradient stops           |    17 |
// | CompositionVisualSurface |     - |
// ------------------------------------
using Microsoft.Graphics;
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Composition;
using System;
using System.Collections.Generic;
using System.Numerics;
using Windows.UI;

namespace LocalSendDotNet
{
    // Name:        LocalSend Splash Logo
    // Frame rate:  60 fps
    // Frame count: 80
    // Duration:    1333.3 mS
    // ______________________________________________________________________________________________
    // | Marker  |            Constant             |     Start      | Duration |      Progress      |
    // |         |           start | end           |  Frame |    mS |       mS |        start | end |
    // |_________|_________________|_______________|________|_______|__________|______________|_____|
    // | settled | M_settled_start | M_settled_end |   56.0 | 933.3 |    400.0 | 0.700625002F | 1d  |
    // ----------------------------------------------------------------------------------------------
    public sealed partial class SplashLogo
        : Microsoft.UI.Xaml.Controls.IAnimatedVisualSource
        , Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2
    {
        // Animation duration: 1.333 seconds.
        internal const long c_durationTicks = 13333333;

        // Marker: settled.
        internal const float M_settled_start = 0.700625002F;

        // Marker: settled.
        internal const float M_settled_end = 1F;

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor)
        {
            object ignored = null;
            return TryCreateAnimatedVisual(compositor, out ignored);
        }

        public Microsoft.UI.Xaml.Controls.IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;

            var res = 
                new SplashLogo_AnimatedVisual(
                    compositor
                    );
                res.CreateAnimations();
                return res;
        }

        /// <summary>
        /// Gets the number of frames in the animation.
        /// </summary>
        public double FrameCount => 80d;

        /// <summary>
        /// Gets the frame rate of the animation.
        /// </summary>
        public double Framerate => 60d;

        /// <summary>
        /// Gets the duration of the animation.
        /// </summary>
        public TimeSpan Duration => TimeSpan.FromTicks(13333333);

        /// <summary>
        /// Converts a zero-based frame number to the corresponding progress value denoting the
        /// start of the frame.
        /// </summary>
        public double FrameToProgress(double frameNumber)
        {
            return frameNumber / 80d;
        }

        /// <summary>
        /// Returns a map from marker names to corresponding progress values.
        /// </summary>
        public IReadOnlyDictionary<string, double> Markers =>
            new Dictionary<string, double>
            {
                { "settled", 0.700625 },
            };

        /// <summary>
        /// Sets the color property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetColorProperty(string propertyName, Color value)
        {
        }

        /// <summary>
        /// Sets the scalar property with the given name, or does nothing if no such property
        /// exists.
        /// </summary>
        public void SetScalarProperty(string propertyName, double value)
        {
        }

        sealed partial class SplashLogo_AnimatedVisual
            : Microsoft.UI.Xaml.Controls.IAnimatedVisual
            , Microsoft.UI.Xaml.Controls.IAnimatedVisual2
        {
            const long c_durationTicks = 13333333;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            AnimationController _animationController_0;
            CompositionColorBrush _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0;
            CompositionColorBrush _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1;
            CompositionColorBrush _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2;
            CompositionColorBrush _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite;
            CompositionColorBrush _colorBrush_AlmostAzure_FFEFFFFC;
            CompositionColorGradientStop _animatedGradientStop_0_0;
            CompositionColorGradientStop _animatedGradientStop_0_1;
            CompositionColorGradientStop _animatedGradientStop_0_2;
            CompositionColorGradientStop _animatedGradientStop_0_3;
            CompositionColorGradientStop _animatedGradientStop_0_4;
            CompositionColorGradientStop _animatedGradientStop_0_5;
            CompositionColorGradientStop _animatedGradientStop_0p4_0;
            CompositionColorGradientStop _animatedGradientStop_0p4_1;
            CompositionColorGradientStop _animatedGradientStop_0p48;
            CompositionColorGradientStop _animatedGradientStop_1_0;
            CompositionColorGradientStop _animatedGradientStop_1_1;
            CompositionColorGradientStop _animatedGradientStop_1_2;
            CompositionColorGradientStop _animatedGradientStop_1_3;
            CompositionContainerShape _containerShape;
            CompositionLinearGradientBrush _linearGradientBrush_0;
            CompositionLinearGradientBrush _linearGradientBrush_1;
            CompositionPathGeometry _pathGeometry_0;
            CompositionPathGeometry _pathGeometry_1;
            CompositionPathGeometry _pathGeometry_2;
            CompositionPathGeometry _pathGeometry_3;
            CompositionPathGeometry _pathGeometry_4;
            CompositionPathGeometry _pathGeometry_5;
            CompositionPathGeometry _pathGeometry_6;
            CompositionPathGeometry _pathGeometry_7;
            CompositionRadialGradientBrush _radialGradientBrush;
            CompositionRoundedRectangleGeometry _roundedRectangle_256;
            ContainerVisual _root;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            CubicBezierEasingFunction _cubicBezierEasingFunction_1;
            CubicBezierEasingFunction _cubicBezierEasingFunction_2;
            ExpressionAnimation _colorExpressionAnimation_0;
            ExpressionAnimation _colorExpressionAnimation_1;
            ExpressionAnimation _colorExpressionAnimation_2;
            ExpressionAnimation _colorExpressionAnimation_3;
            ExpressionAnimation _colorExpressionAnimation_4;
            ExpressionAnimation _colorExpressionAnimation_5;
            ScalarKeyFrameAnimation _opacity0ScalarAnimation_0_to_255;
            StepEasingFunction _holdThenStepEasingFunction;

            void BindProperty(
                CompositionObject target,
                string animatedPropertyName,
                string expression,
                string referenceParameterName,
                CompositionObject referencedObject)
            {
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = expression;
                _reusableExpressionAnimation.SetReferenceParameter(referenceParameterName, referencedObject);
                target.StartAnimation(animatedPropertyName, _reusableExpressionAnimation);
            }

            ColorKeyFrameAnimation CreateColorKeyFrameAnimation(float initialProgress, Color initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateColorKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InterpolationColorSpace = CompositionColorSpace.Rgb;
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            ScalarKeyFrameAnimation CreateScalarKeyFrameAnimation(float initialProgress, float initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            Vector2KeyFrameAnimation CreateVector2KeyFrameAnimation(float initialProgress, Vector2 initialValue, CompositionEasingFunction initialEasingFunction)
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(initialProgress, initialValue, initialEasingFunction);
                return result;
            }

            AnimationController AnimationController_0()
            {
                if (_animationController_0 != null) { return _animationController_0; }
                var result = _animationController_0 = _c.CreateAnimationController();
                result.Pause();
                BindProperty(_animationController_0, "Progress", "_.Progress", "_", _root);
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Ring Dash 5
            CanvasGeometry Geometry_0()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(84.6412964F, 65.5819016F));
                    builder.AddCubicBezier(new Vector2(107.650703F, 49.5984001F), new Vector2(137.587601F, 47.5699997F), new Vector2(162.542694F, 60.3036003F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Ring Dash 5
            CanvasGeometry Geometry_1()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(58.1408005F, 157.927994F));
                    builder.AddCubicBezier(new Vector2(47.1082993F, 132.175598F), new Vector2(51.1385002F, 102.441902F), new Vector2(68.6280975F, 80.5554962F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Ring Dash 5
            CanvasGeometry Geometry_2()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(143.275696F, 202.449005F));
                    builder.AddCubicBezier(new Vector2(115.831299F, 208.080093F), new Vector2(87.5146027F, 198.155807F), new Vector2(69.5902023F, 176.623993F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Ring Dash 5
            CanvasGeometry Geometry_3()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(204F, 128F));
                    builder.AddCubicBezier(new Vector2(204F, 156.016098F), new Vector2(188.586594F, 181.760193F), new Vector2(163.891495F, 194.990997F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Ring Dash 5
            CanvasGeometry Geometry_4()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(180.429306F, 72.9803009F));
                    builder.AddCubicBezier(new Vector2(195.481506F, 87.3238983F), new Vector2(204F, 107.208F), new Vector2(204F, 128F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Head Lower
            CanvasGeometry Geometry_5()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(179F, 128F));
                    builder.AddLine(new Vector2(150F, 157F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Head Lower
            CanvasGeometry Geometry_6()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(179F, 128F));
                    builder.AddLine(new Vector2(150F, 99F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - - Layer aggregator
            // - - ShapeGroup: Head Lower
            CanvasGeometry Geometry_7()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.BeginFigure(new Vector2(79F, 128F));
                    builder.AddLine(new Vector2(177F, 128F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Head Lower
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xEF, 0xFF, 0xFC), HoldThenStepEasingFunction());
                // Frame 34.
                // TransparentAlmostAzure_00EFFFFC
                result.InsertKeyFrame(0.425000012F, Color.FromArgb(0x00, 0xEF, 0xFF, 0xFC), HoldThenStepEasingFunction());
                // Frame 40.
                // AlmostAzure_FFEFFFFC
                result.InsertKeyFrame(0.5F, Color.FromArgb(0xFF, 0xEF, 0xFF, 0xFC), CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Head Lower
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xEF, 0xFF, 0xFC), HoldThenStepEasingFunction());
                // Frame 32.
                // TransparentAlmostAzure_00EFFFFC
                result.InsertKeyFrame(0.400000006F, Color.FromArgb(0x00, 0xEF, 0xFF, 0xFC), HoldThenStepEasingFunction());
                // Frame 38.
                // AlmostAzure_FFEFFFFC
                result.InsertKeyFrame(0.474999994F, Color.FromArgb(0xFF, 0xEF, 0xFF, 0xFC), CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Head Lower
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xEF, 0xFF, 0xFC), HoldThenStepEasingFunction());
                // Frame 6.
                // TransparentAlmostAzure_00EFFFFC
                result.InsertKeyFrame(0.075000003F, Color.FromArgb(0x00, 0xEF, 0xFF, 0xFC), HoldThenStepEasingFunction());
                // Frame 12.
                // AlmostAzure_FFEFFFFC
                result.InsertKeyFrame(0.150000006F, Color.FromArgb(0xFF, 0xEF, 0xFF, 0xFC), CubicBezierEasingFunction_1());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Color
            ColorKeyFrameAnimation ColorAnimation_TransparentWhite_to_SemiTransparentWhite()
            {
                // Frame 0.
                var result = CreateColorKeyFrameAnimation(0F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF), HoldThenStepEasingFunction());
                // Frame 16.
                // SemiTransparentWhite
                result.InsertKeyFrame(0.200000003F, Color.FromArgb(0x38, 0xFF, 0xFF, 0xFF), CubicBezierEasingFunction_0());
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Head Lower
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0()
            {
                if (_animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0 != null) { return _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0; }
                var result = _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0 = _c.CreateColorBrush();
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Head Lower
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1()
            {
                if (_animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1 != null) { return _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1; }
                var result = _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1 = _c.CreateColorBrush();
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Head Lower
            CompositionColorBrush AnimatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2()
            {
                if (_animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2 != null) { return _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2; }
                var result = _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2 = _c.CreateColorBrush();
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Rim
            CompositionColorBrush AnimatedColorBrush_TransparentWhite_to_SemiTransparentWhite()
            {
                if (_animatedColorBrush_TransparentWhite_to_SemiTransparentWhite != null) { return _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite; }
                var result = _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite = _c.CreateColorBrush();
                return result;
            }

            CompositionColorBrush ColorBrush_AlmostAzure_FFEFFFFC()
            {
                return (_colorBrush_AlmostAzure_FFEFFFFC == null)
                    ? _colorBrush_AlmostAzure_FFEFFFFC = _c.CreateColorBrush(Color.FromArgb(0xFF, 0xEF, 0xFF, 0xFC))
                    : _colorBrush_AlmostAzure_FFEFFFFC;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_0()
            {
                if (_animatedGradientStop_0_0 != null) { return _animatedGradientStop_0_0; }
                var result = _animatedGradientStop_0_0 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0_1()
            {
                if (_animatedGradientStop_0_1 != null) { return _animatedGradientStop_0_1; }
                var result = _animatedGradientStop_0_1 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_2()
            {
                if (_animatedGradientStop_0_2 != null) { return _animatedGradientStop_0_2; }
                var result = _animatedGradientStop_0_2 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0_3()
            {
                if (_animatedGradientStop_0_3 != null) { return _animatedGradientStop_0_3; }
                var result = _animatedGradientStop_0_3 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 0
            CompositionColorGradientStop AnimatedGradientStop_0_4()
            {
                if (_animatedGradientStop_0_4 != null) { return _animatedGradientStop_0_4; }
                var result = _animatedGradientStop_0_4 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 1
            CompositionColorGradientStop AnimatedGradientStop_0_5()
            {
                if (_animatedGradientStop_0_5 != null) { return _animatedGradientStop_0_5; }
                var result = _animatedGradientStop_0_5 = _c.CreateColorGradientStop(0F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_0p4_0()
            {
                if (_animatedGradientStop_0p4_0 != null) { return _animatedGradientStop_0p4_0; }
                var result = _animatedGradientStop_0p4_0 = _c.CreateColorGradientStop(0.400000006F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 3
            CompositionColorGradientStop AnimatedGradientStop_0p4_1()
            {
                if (_animatedGradientStop_0p4_1 != null) { return _animatedGradientStop_0p4_1; }
                var result = _animatedGradientStop_0p4_1 = _c.CreateColorGradientStop(0.400000006F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 2
            CompositionColorGradientStop AnimatedGradientStop_0p48()
            {
                if (_animatedGradientStop_0p48 != null) { return _animatedGradientStop_0p48; }
                var result = _animatedGradientStop_0p48 = _c.CreateColorGradientStop(0.479999989F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                BindProperty(_animatedGradientStop_0p48, "Color", "ColorRGB(my.Opacity0,0,155,163)", "my", LinearGradientBrush_1());
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 4
            CompositionColorGradientStop AnimatedGradientStop_1_0()
            {
                if (_animatedGradientStop_1_0 != null) { return _animatedGradientStop_1_0; }
                var result = _animatedGradientStop_1_0 = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 5
            CompositionColorGradientStop AnimatedGradientStop_1_1()
            {
                if (_animatedGradientStop_1_1 != null) { return _animatedGradientStop_1_1; }
                var result = _animatedGradientStop_1_1 = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 3
            CompositionColorGradientStop AnimatedGradientStop_1_2()
            {
                if (_animatedGradientStop_1_2 != null) { return _animatedGradientStop_1_2; }
                var result = _animatedGradientStop_1_2 = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 4
            CompositionColorGradientStop AnimatedGradientStop_1_3()
            {
                if (_animatedGradientStop_1_3 != null) { return _animatedGradientStop_1_3; }
                var result = _animatedGradientStop_1_3 = _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0x00, 0x00, 0x00));
                return result;
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 2
            CompositionColorGradientStop GradientStop_0p4_TransparentWhite_0()
            {
                return _c.CreateColorGradientStop(0.400000006F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF));
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 3
            CompositionColorGradientStop GradientStop_0p4_TransparentWhite_1()
            {
                return _c.CreateColorGradientStop(0.400000006F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF));
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 4
            CompositionColorGradientStop GradientStop_1_TransparentWhite_0()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF));
            }

            // - - - Layer aggregator
            // - ShapeGroup: Rim
            // Stop 5
            CompositionColorGradientStop GradientStop_1_TransparentWhite_1()
            {
                return _c.CreateColorGradientStop(1F, Color.FromArgb(0x00, 0xFF, 0xFF, 0xFF));
            }

            // Layer aggregator
            CompositionContainerShape ContainerShape()
            {
                if (_containerShape != null) { return _containerShape; }
                var result = _containerShape = _c.CreateContainerShape();
                result.CenterPoint = new Vector2(128F, 128F);
                var shapes = result.Shapes;
                // ShapeGroup: Rim
                shapes.Add(SpriteShape_00());
                // ShapeGroup: Rim
                shapes.Add(SpriteShape_01());
                // ShapeGroup: Rim
                shapes.Add(SpriteShape_02());
                // ShapeGroup: Rim
                shapes.Add(SpriteShape_03());
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Rim
            CompositionLinearGradientBrush LinearGradientBrush_0()
            {
                if (_linearGradientBrush_0 != null) { return _linearGradientBrush_0; }
                var result = _linearGradientBrush_0 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_0());
                colorStops.Add(AnimatedGradientStop_0_1());
                colorStops.Add(GradientStop_0p4_TransparentWhite_0());
                colorStops.Add(GradientStop_0p4_TransparentWhite_1());
                colorStops.Add(AnimatedGradientStop_1_0());
                colorStops.Add(AnimatedGradientStop_1_1());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(0F, -128F);
                result.EndPoint = new Vector2(0F, 128F);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Rim
            CompositionLinearGradientBrush LinearGradientBrush_1()
            {
                if (_linearGradientBrush_1 != null) { return _linearGradientBrush_1; }
                var result = _linearGradientBrush_1 = _c.CreateLinearGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_4());
                colorStops.Add(AnimatedGradientStop_0_5());
                colorStops.Add(AnimatedGradientStop_0p48());
                colorStops.Add(AnimatedGradientStop_1_2());
                colorStops.Add(AnimatedGradientStop_1_3());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.StartPoint = new Vector2(-81.9199982F, -128F);
                result.EndPoint = new Vector2(81.9199982F, 128F);
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Ring Dash 5
            CompositionPathGeometry PathGeometry_0()
            {
                if (_pathGeometry_0 != null) { return _pathGeometry_0; }
                var result = _pathGeometry_0 = _c.CreatePathGeometry(new CompositionPath(Geometry_0()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Ring Dash 5
            CompositionPathGeometry PathGeometry_1()
            {
                if (_pathGeometry_1 != null) { return _pathGeometry_1; }
                var result = _pathGeometry_1 = _c.CreatePathGeometry(new CompositionPath(Geometry_1()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Ring Dash 5
            CompositionPathGeometry PathGeometry_2()
            {
                if (_pathGeometry_2 != null) { return _pathGeometry_2; }
                var result = _pathGeometry_2 = _c.CreatePathGeometry(new CompositionPath(Geometry_2()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Ring Dash 5
            CompositionPathGeometry PathGeometry_3()
            {
                if (_pathGeometry_3 != null) { return _pathGeometry_3; }
                var result = _pathGeometry_3 = _c.CreatePathGeometry(new CompositionPath(Geometry_3()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Ring Dash 5
            CompositionPathGeometry PathGeometry_4()
            {
                if (_pathGeometry_4 != null) { return _pathGeometry_4; }
                var result = _pathGeometry_4 = _c.CreatePathGeometry(new CompositionPath(Geometry_4()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Head Lower
            CompositionPathGeometry PathGeometry_5()
            {
                if (_pathGeometry_5 != null) { return _pathGeometry_5; }
                var result = _pathGeometry_5 = _c.CreatePathGeometry(new CompositionPath(Geometry_5()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Head Lower
            CompositionPathGeometry PathGeometry_6()
            {
                if (_pathGeometry_6 != null) { return _pathGeometry_6; }
                var result = _pathGeometry_6 = _c.CreatePathGeometry(new CompositionPath(Geometry_6()));
                return result;
            }

            // - Layer aggregator
            // ShapeGroup: Head Lower
            CompositionPathGeometry PathGeometry_7()
            {
                if (_pathGeometry_7 != null) { return _pathGeometry_7; }
                var result = _pathGeometry_7 = _c.CreatePathGeometry(new CompositionPath(Geometry_7()));
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Rim
            CompositionRadialGradientBrush RadialGradientBrush()
            {
                if (_radialGradientBrush != null) { return _radialGradientBrush; }
                var result = _radialGradientBrush = _c.CreateRadialGradientBrush();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Opacity0", 0F);
                var colorStops = result.ColorStops;
                colorStops.Add(AnimatedGradientStop_0_2());
                colorStops.Add(AnimatedGradientStop_0_3());
                colorStops.Add(AnimatedGradientStop_0p4_0());
                colorStops.Add(AnimatedGradientStop_0p4_1());
                colorStops.Add(GradientStop_1_TransparentWhite_0());
                colorStops.Add(GradientStop_1_TransparentWhite_1());
                result.MappingMode = CompositionMappingMode.Absolute;
                result.EllipseCenter = new Vector2(71.6800003F, 46.0800018F);
                result.EllipseRadius = new Vector2(179.200012F, 179.200012F);
                return result;
            }

            // - - Layer aggregator
            // ShapeGroup: Rim
            // Rim Rectangle.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_253p5()
            {
                var result = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(54.75F, 54.75F);
                result.Offset = new Vector2(1.25F, 1.25F);
                result.Size = new Vector2(253.5F, 253.5F);
                return result;
            }

            // Sheen Rectangle.RectangleGeometry
            CompositionRoundedRectangleGeometry RoundedRectangle_256()
            {
                if (_roundedRectangle_256 != null) { return _roundedRectangle_256; }
                var result = _roundedRectangle_256 = _c.CreateRoundedRectangleGeometry();
                result.CornerRadius = new Vector2(56F, 56F);
                result.Offset = new Vector2(0F, 0F);
                result.Size = new Vector2(256F, 256F);
                return result;
            }

            // - Layer aggregator
            // Rim Rectangle
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_253p5());
                result.StrokeBrush = AnimatedColorBrush_TransparentWhite_to_SemiTransparentWhite();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 2.5F;
                return result;
            }

            // - Layer aggregator
            // Sheen Rectangle
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_256());
                result.FillBrush = LinearGradientBrush_0();
                return result;
            }

            // - Layer aggregator
            // Spot Rectangle
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_256());
                result.FillBrush = RadialGradientBrush();
                return result;
            }

            // - Layer aggregator
            // Plate Rectangle
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape(RoundedRectangle_256());
                result.FillBrush = LinearGradientBrush_1();
                return result;
            }

            // Layer aggregator
            // Arc 5
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape(PathGeometry_0());
                result.StrokeBrush = ColorBrush_AlmostAzure_FFEFFFFC();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Arc 4
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape(PathGeometry_1());
                result.StrokeBrush = ColorBrush_AlmostAzure_FFEFFFFC();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Arc 3
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape(PathGeometry_2());
                result.StrokeBrush = ColorBrush_AlmostAzure_FFEFFFFC();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Arc 2
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape(PathGeometry_3());
                result.StrokeBrush = ColorBrush_AlmostAzure_FFEFFFFC();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Arc 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape(PathGeometry_4());
                result.StrokeBrush = ColorBrush_AlmostAzure_FFEFFFFC();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Lower Wing
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape(PathGeometry_5());
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Upper Wing
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape(PathGeometry_6());
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // Layer aggregator
            // Shaft Path
            CompositionSpriteShape SpriteShape_11()
            {
                var result = _c.CreateSpriteShape(PathGeometry_7());
                result.StrokeBrush = AnimatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2();
                result.StrokeDashCap = CompositionStrokeCap.Round;
                result.StrokeStartCap = CompositionStrokeCap.Round;
                result.StrokeEndCap = CompositionStrokeCap.Round;
                result.StrokeLineJoin = CompositionStrokeLineJoin.Round;
                result.StrokeMiterLimit = 2F;
                result.StrokeThickness = 18F;
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                if (_root != null) { return _root; }
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0F);
                // Layer aggregator
                result.Children.InsertAtTop(ShapeVisual_0());
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return (_cubicBezierEasingFunction_0 == null)
                    ? _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0F, 0.649999976F), new Vector2(0.50999999F, 0.99000001F))
                    : _cubicBezierEasingFunction_0;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return (_cubicBezierEasingFunction_1 == null)
                    ? _cubicBezierEasingFunction_1 = _c.CreateCubicBezierEasingFunction(new Vector2(0.200000003F, 0.75F), new Vector2(0.340000004F, 0.939999998F))
                    : _cubicBezierEasingFunction_1;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_2()
            {
                return (_cubicBezierEasingFunction_2 == null)
                    ? _cubicBezierEasingFunction_2 = _c.CreateCubicBezierEasingFunction(new Vector2(0.939999998F, 0.75F), new Vector2(0.340000004F, 0.939999998F))
                    : _cubicBezierEasingFunction_2;
            }

            ExpressionAnimation ColorExpressionAnimation_0()
            {
                if (_colorExpressionAnimation_0 != null) { return _colorExpressionAnimation_0; }
                var result = _colorExpressionAnimation_0 = _c.CreateExpressionAnimation("ColorRGB(0.1176471*my.Opacity0,255,255,255)");
                result.SetReferenceParameter("my", LinearGradientBrush_0().Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_1()
            {
                if (_colorExpressionAnimation_1 != null) { return _colorExpressionAnimation_1; }
                var result = _colorExpressionAnimation_1 = _c.CreateExpressionAnimation("ColorRGB(0.1372549*my.Opacity0,0,52,60)");
                result.SetReferenceParameter("my", LinearGradientBrush_0().Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_2()
            {
                if (_colorExpressionAnimation_2 != null) { return _colorExpressionAnimation_2; }
                var result = _colorExpressionAnimation_2 = _c.CreateExpressionAnimation("ColorRGB(0.1568628*my.Opacity0,255,255,255)");
                result.SetReferenceParameter("my", RadialGradientBrush().Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_3()
            {
                if (_colorExpressionAnimation_3 != null) { return _colorExpressionAnimation_3; }
                var result = _colorExpressionAnimation_3 = _c.CreateExpressionAnimation("ColorRGB(0.03921569*my.Opacity0,255,255,255)");
                result.SetReferenceParameter("my", RadialGradientBrush().Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_4()
            {
                if (_colorExpressionAnimation_4 != null) { return _colorExpressionAnimation_4; }
                var result = _colorExpressionAnimation_4 = _c.CreateExpressionAnimation("ColorRGB(my.Opacity0,20,196,194)");
                result.SetReferenceParameter("my", LinearGradientBrush_1().Properties);
                return result;
            }

            ExpressionAnimation ColorExpressionAnimation_5()
            {
                if (_colorExpressionAnimation_5 != null) { return _colorExpressionAnimation_5; }
                var result = _colorExpressionAnimation_5 = _c.CreateExpressionAnimation("ColorRGB(my.Opacity0,11,101,112)");
                result.SetReferenceParameter("my", LinearGradientBrush_1().Properties);
                return result;
            }

            // Opacity0
            ScalarKeyFrameAnimation Opacity0ScalarAnimation_0_to_255()
            {
                // Frame 0.
                if (_opacity0ScalarAnimation_0_to_255 != null) { return _opacity0ScalarAnimation_0_to_255; }
                var result = _opacity0ScalarAnimation_0_to_255 = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 16.
                result.InsertKeyFrame(0.200000003F, 255F, CubicBezierEasingFunction_0());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Ring Dash 5
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_0()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 32.
                result.InsertKeyFrame(0.400000006F, 0F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.625F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Ring Dash 5
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_1()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 26.
                result.InsertKeyFrame(0.324999988F, 0F, HoldThenStepEasingFunction());
                // Frame 44.
                result.InsertKeyFrame(0.550000012F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Ring Dash 5
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_2()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 20.
                result.InsertKeyFrame(0.25F, 0F, HoldThenStepEasingFunction());
                // Frame 38.
                result.InsertKeyFrame(0.474999994F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Ring Dash 5
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_3()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 14.
                result.InsertKeyFrame(0.174999997F, 0F, HoldThenStepEasingFunction());
                // Frame 32.
                result.InsertKeyFrame(0.400000006F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Ring Dash 5
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_4()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 8.
                result.InsertKeyFrame(0.100000001F, 0F, HoldThenStepEasingFunction());
                // Frame 26.
                result.InsertKeyFrame(0.324999988F, 1F, CubicBezierEasingFunction_1());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Head Lower
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_5()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 34.
                result.InsertKeyFrame(0.425000012F, 0F, HoldThenStepEasingFunction());
                // Frame 52.
                result.InsertKeyFrame(0.649999976F, 1F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Head Lower
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_6()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 32.
                result.InsertKeyFrame(0.400000006F, 0F, HoldThenStepEasingFunction());
                // Frame 50.
                result.InsertKeyFrame(0.625F, 1F, CubicBezierEasingFunction_2());
                return result;
            }

            // - - Layer aggregator
            // - ShapeGroup: Head Lower
            // TrimEnd
            ScalarKeyFrameAnimation TrimEndScalarAnimation_0_to_1_7()
            {
                // Frame 0.
                var result = CreateScalarKeyFrameAnimation(0F, 0F, HoldThenStepEasingFunction());
                // Frame 6.
                result.InsertKeyFrame(0.075000003F, 0F, HoldThenStepEasingFunction());
                // Frame 34.
                result.InsertKeyFrame(0.425000012F, 1F, _c.CreateCubicBezierEasingFunction(new Vector2(1F, 0.49000001F), new Vector2(0F, 0.550000012F)));
                return result;
            }

            // Layer aggregator
            ShapeVisual ShapeVisual_0()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(256F, 256F);
                var shapes = result.Shapes;
                shapes.Add(ContainerShape());
                // ShapeGroup: Ring Dash 5
                shapes.Add(SpriteShape_04());
                // ShapeGroup: Ring Dash 5
                shapes.Add(SpriteShape_05());
                // ShapeGroup: Ring Dash 5
                shapes.Add(SpriteShape_06());
                // ShapeGroup: Ring Dash 5
                shapes.Add(SpriteShape_07());
                // ShapeGroup: Ring Dash 5
                shapes.Add(SpriteShape_08());
                // ShapeGroup: Head Lower
                shapes.Add(SpriteShape_09());
                // ShapeGroup: Head Lower
                shapes.Add(SpriteShape_10());
                // ShapeGroup: Head Lower
                shapes.Add(SpriteShape_11());
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                if (_holdThenStepEasingFunction != null) { return _holdThenStepEasingFunction; }
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // - Layer aggregator
            // Scale
            Vector2KeyFrameAnimation ScaleVector2Animation()
            {
                // Frame 0.
                var result = CreateVector2KeyFrameAnimation(0F, new Vector2(0.899999976F, 0.899999976F), HoldThenStepEasingFunction());
                // Frame 28.
                result.InsertKeyFrame(0.349999994F, new Vector2(1F, 1F), CubicBezierEasingFunction_0());
                return result;
            }

            internal SplashLogo_AnimatedVisual(
                Compositor compositor
                )
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            public Visual RootVisual => _root;
            public TimeSpan Duration => TimeSpan.FromTicks(c_durationTicks);
            public Vector2 Size => new Vector2(256F, 256F);
            void IDisposable.Dispose() => _root?.Dispose();

            public void CreateAnimations()
            {
                _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0.StartAnimation("Color", ColorAnimation_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0(), AnimationController_0());
                _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1.StartAnimation("Color", ColorAnimation_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1(), AnimationController_0());
                _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2.StartAnimation("Color", ColorAnimation_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2(), AnimationController_0());
                _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite.StartAnimation("Color", ColorAnimation_TransparentWhite_to_SemiTransparentWhite(), AnimationController_0());
                _animatedGradientStop_0_0.StartAnimation("Color", ColorExpressionAnimation_0());
                _animatedGradientStop_0_1.StartAnimation("Color", ColorExpressionAnimation_0());
                _animatedGradientStop_0_2.StartAnimation("Color", ColorExpressionAnimation_2());
                _animatedGradientStop_0_3.StartAnimation("Color", ColorExpressionAnimation_2());
                _animatedGradientStop_0_4.StartAnimation("Color", ColorExpressionAnimation_4());
                _animatedGradientStop_0_5.StartAnimation("Color", ColorExpressionAnimation_4());
                _animatedGradientStop_0p4_0.StartAnimation("Color", ColorExpressionAnimation_3());
                _animatedGradientStop_0p4_1.StartAnimation("Color", ColorExpressionAnimation_3());
                _animatedGradientStop_1_0.StartAnimation("Color", ColorExpressionAnimation_1());
                _animatedGradientStop_1_1.StartAnimation("Color", ColorExpressionAnimation_1());
                _animatedGradientStop_1_2.StartAnimation("Color", ColorExpressionAnimation_5());
                _animatedGradientStop_1_3.StartAnimation("Color", ColorExpressionAnimation_5());
                _containerShape.StartAnimation("Scale", ScaleVector2Animation(), AnimationController_0());
                _linearGradientBrush_0.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_0_to_255(), AnimationController_0());
                _linearGradientBrush_1.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_0_to_255(), AnimationController_0());
                _pathGeometry_0.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_0(), AnimationController_0());
                _pathGeometry_1.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_1(), AnimationController_0());
                _pathGeometry_2.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_2(), AnimationController_0());
                _pathGeometry_3.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_3(), AnimationController_0());
                _pathGeometry_4.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_4(), AnimationController_0());
                _pathGeometry_5.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_5(), AnimationController_0());
                _pathGeometry_6.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_6(), AnimationController_0());
                _pathGeometry_7.StartAnimation("TrimEnd", TrimEndScalarAnimation_0_to_1_7(), AnimationController_0());
                _radialGradientBrush.Properties.StartAnimation("Opacity0", Opacity0ScalarAnimation_0_to_255(), AnimationController_0());
            }

            public void DestroyAnimations()
            {
                _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_0.StopAnimation("Color");
                _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_1.StopAnimation("Color");
                _animatedColorBrush_TransparentAlmostAzure_00EFFFFC_to_AlmostAzure_FFEFFFFC_2.StopAnimation("Color");
                _animatedColorBrush_TransparentWhite_to_SemiTransparentWhite.StopAnimation("Color");
                _animatedGradientStop_0_0.StopAnimation("Color");
                _animatedGradientStop_0_1.StopAnimation("Color");
                _animatedGradientStop_0_2.StopAnimation("Color");
                _animatedGradientStop_0_3.StopAnimation("Color");
                _animatedGradientStop_0_4.StopAnimation("Color");
                _animatedGradientStop_0_5.StopAnimation("Color");
                _animatedGradientStop_0p4_0.StopAnimation("Color");
                _animatedGradientStop_0p4_1.StopAnimation("Color");
                _animatedGradientStop_1_0.StopAnimation("Color");
                _animatedGradientStop_1_1.StopAnimation("Color");
                _animatedGradientStop_1_2.StopAnimation("Color");
                _animatedGradientStop_1_3.StopAnimation("Color");
                _containerShape.StopAnimation("Scale");
                _linearGradientBrush_0.Properties.StopAnimation("Opacity0");
                _linearGradientBrush_1.Properties.StopAnimation("Opacity0");
                _pathGeometry_0.StopAnimation("TrimEnd");
                _pathGeometry_1.StopAnimation("TrimEnd");
                _pathGeometry_2.StopAnimation("TrimEnd");
                _pathGeometry_3.StopAnimation("TrimEnd");
                _pathGeometry_4.StopAnimation("TrimEnd");
                _pathGeometry_5.StopAnimation("TrimEnd");
                _pathGeometry_6.StopAnimation("TrimEnd");
                _pathGeometry_7.StopAnimation("TrimEnd");
                _radialGradientBrush.Properties.StopAnimation("Opacity0");
            }

        }
    }
}
